# -*- coding: utf-8 -*-
"""인공지능개론과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wWf_8E28csIrrPl383LuFjne7yWkYyZ
"""

import sys
!sudo add-apt-repository ppa:saiarcot895/chromium-beta
!sudo apt remove chromium-browser
!sudo snap remove chromium
!sudo apt install chromium-browser
!pip3 install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
webdriver_service = Service('/usr/bin/chromedriver')
driver = webdriver.Chrome(service = webdriver_service, options=options)
url = 'https://www.molit.go.kr/USR/NEWS/m_71/lst.jsp'
driver.get(url)

columns = ['순위', '기사 제목', '분류', '기사 작성일']
rank = []
title = []
journal = []
date = []
for i in range(1, 11):
    rank.append(i)
    title.append(driver.find_element(By.CSS_SELECTOR, f"#cont-body > table > tbody > tr:nth-child({i}) > td.bd_title > a").text)
    journal.append(driver.find_element(By.XPATH, f'/html/body/div[3]/section/div[2]/article/table/tbody/tr[{i}]/td[3]').text)
    date.append(driver.find_element(By.XPATH, f'/html/body/div[3]/section/div[2]/article/table/tbody/tr[{i}]/td[4]').text)

import pandas as pd
df = pd.DataFrame({columns[0]: rank,
columns[1]: title,
columns[2]: journal,
columns[3]: date}, columns=columns)
df.head()

df.to_csv('news.csv', index=False)

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import csv
#CSV 파일 읽어오기
f = open('news.csv', 'r')
rdr = csv.reader(f)
f.close
title = ''
for line in rdr:
    title = title + ' ' + line[1]
print(title)

title = title[6:]
print(title)

!pip install konlpy
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from collections import Counter
from konlpy.tag import Okt
import numpy as np

#문자열 분석하기
okt = Okt()
nouns = okt.nouns(title)
words = [n for n in nouns if len(n) > 1]
c = Counter(words)
#워드클라우드 생성하기
wc = WordCloud(font_path='/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf',\
scale=2.0, colormap='Spectral')
gen = wc.generate_from_frequencies(c)
plt.figure()
plt.imshow(gen)

